from pathlib import Path

from lxcat_data_parser import CrossSectionSet


def parse_lxcat_data(filename: str) -> CrossSectionSet:
    """Parse LXCat data file and return a CrossSectionSet object.

    Parameters
    ----------
    filename : str
        Path to the LXCat data file to be parsed.

    Raises
    ------
    TypeError
        If filename is not a string.
    ValueError
        If filename is an empty string.
    """

    if not isinstance(filename, str):
        raise TypeError("filename must be of type str")
    if not filename.strip():
        raise ValueError("filename cannot be an empty string")

    return CrossSectionSet(filename)


def _clear_file(output_file: Path | str) -> None:
    """Clear the contents of a given file.

    Parameters
    ----------
    output_file : Path | str
        The path to the file to clear.
    """

    output_file = Path(output_file)

    if not output_file.exists():
        return

    output_file.write_text("")


def _append_to_file(output_file: Path | str, data: str) -> None:
    """Append text to a given file.

    Parameters
    ----------
    output_file : Path | str
        Path to the file to append to.
    data : str
        The text to append to the file.
    """

    output_file = Path(output_file)

    if not output_file.exists():
        output_file.touch()

    original_text = output_file.read_text()
    needs_newline = bool(original_text)

    output_file.write_text(original_text + "\n" * needs_newline + data)


def _write_header(output_file: Path | str) -> None:
    """Write header to output file.

    Parameters
    ----------
    output_file : Path | str
        Path to the output file.
    """

    output_file = Path(output_file)

    _append_to_file(
        output_file,
        "################################################################################",
    )
    _append_to_file(
        output_file,
        "#                          File generated by xs2arr.                           #",
    )
    _append_to_file(
        output_file,
        "################################################################################",
    )


def _write_reaction_header(
    output_file: Path | str, reaction_type: str = "default"
) -> None:
    """Write reaction header to output file.

    Parameters
    ----------
    output_file : Path | str
        The path to the output file.
    reaction_type: str
        The type of reaction being written.
    """

    output_file = Path(output_file)

    _append_to_file(output_file, f"begin:{reaction_type}")
    _append_to_file(
        output_file,
        "  # reaction process;         # threshold E;                   # rate coefficient;                     # description",
    )
    _append_to_file(
        output_file,
        "  ##################################################################################################################",
    )


def _write_reaction_footer(
    output_file: Path | str, reaction_type: str = "default"
) -> None:
    """Write reaction footer to output file.

    Parameters
    ----------
    output_file : Path | str
        The path to the output file.
    reaction_type: str
        The type of reaction being written.
    """

    output_file = Path(output_file)

    _append_to_file(output_file, f"end:{reaction_type}")


def _write_reaction(
    output_file: Path | str, reaction: str, energy: float, a: float, b: float, c: float
) -> None:
    """Write a reaction to the output file.

    Parameters
    ----------
    output_file : Path | str
        File to write to.
    reaction : str
        Process of reaction.
    energy : float
        Energy threshold of process.
    a : float
        Arrhenius parameter a.
    b : float
        Arrhenius parameter b.
    c : float
        Arrhenius parameter c.
    """

    output_file = Path(output_file)

    _append_to_file(
        output_file,
        f"  {reaction}; {energy:>6.2f}_eeV; {a:>6.2E} * T_e_eV^{b:>6.3f} * exp({c:>6.2f}/T_e_eV);",
    )
