# This workflow will install Python dependencies and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Setup uv
      id: setup-uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Print the installed version
      run: echo "Installed uv version is ${{ steps.setup-uv.outputs.uv-version }}"

    - name: Set up Python ${{ matrix.python-version }} and install dependencies
      run: |
        uv python install ${{ matrix.python-version }}
        uv sync --python ${{ matrix.python-version }} --extra test --extra build --frozen

    - name: Test with pytest
      run: |
        uv run pytest -v